---
abstract: 'Easy tracer for DBI'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Tracer
no_index:
  directory:
    - inc
provides:
  DBIx::Tracer:
    file: lib/DBIx/Tracer.pm
    version: 0.01
requires:
  DBI: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
